Repository saucelabs/sauce-docs, pull requests merged in 2021-05, with the labels that each got.

#338 APIF Refactor Phase 1
  docs/api-testing/assertion-components/assert-compares.md
  docs/api-testing/assertion-components/assert-contains.md
  docs/api-testing/assertion-components/assert-equals.md
  docs/api-testing/assertion-components/assert-exists.md
  docs/api-testing/assertion-components/assert-greater.md
  docs/api-testing/assertion-components/assert-in.md
  docs/api-testing/assertion-components/assert-is.md
  docs/api-testing/assertion-components/assert-less.md
  docs/api-testing/assertion-components/assert-matches.md
  docs/api-testing/how-to/create-a-dynamic-header.md
  docs/api-testing/how-to/testing-graphql.md
  docs/api-testing/integrations/connectors/pagerduty.md
  docs/api-testing/integrations/connectors/twilio.md
  docs/api-testing/learn-more/planning-your-test.md
  docs/api-testing/learn-more/the-working-copy-published-tests.md
  docs/api-testing/learn-more/working-with-the-response-object.md
  docs/api-testing/logical-components/each.md
  docs/api-testing/quick-start.md
  docs/api-testing/quick-start/build-from-spec.md
  docs/api-testing/quick-start/composer.md
  docs/api-testing/quick-start/environments-vault-and-overrides-magic.md
  docs/api-testing/quick-start/importing-postman-collections.md
  docs/api-testing/quick-start/introduction-to-integration-testing.md
  docs/api-testing/quick-start/schedule-a-test.md
  docs/api-testing/quick-start/using-the-example-snippets.md
  docs/api-testing/reference/composer-snippets.md
  docs/api-testing/self-hosted/updating-the-api-fortress-license-key.md
  docs/api-testing/self-hosted/using-rds-and-documentdb.md
  sidebars.js
  static/img/api-fortress/2016/03/testControlPanel.jpeg
  static/img/api-fortress/2018/03/schedulerGlobal.jpeg
  static/img/api-fortress/2019/06/CodeView.png
  static/img/api-fortress/2019/06/Screen Shot 2021-04-05 at 5.29.32 PM.png
  static/img/api-fortress/2019/06/Screen-Shot-2019-06-10-at-4.59.14-PM.png
  static/img/api-fortress/2019/06/VisualView.png
  static/img/api-fortress/2019/06/addHeader.png
  static/img/api-fortress/2019/06/examples.png
  static/img/api-fortress/2019/06/existingSnippet.png
  static/img/api-fortress/2019/06/finalScreen.png
  static/img/api-fortress/2019/06/generateTestButton.png
  static/img/api-fortress/2019/06/inputSets.png
  static/img/api-fortress/2019/06/numberpic.png
  static/img/api-fortress/2019/06/screen1.png
  static/img/api-fortress/2019/06/screen2.png
  static/img/api-fortress/2019/06/screen3.png
  static/img/api-fortress/2019/06/sendRequest.png
  static/img/api-fortress/2019/06/snippetInsert.png
  static/img/api-fortress/2019/06/snippetInsertion.png
  static/img/api-fortress/2019/06/snippetList.png
  static/img/api-fortress/2019/06/snippetResult.png
  static/img/api-fortress/2019/06/visual.png
Labels: documentation

#358 Native FW CLI changes
  docs/dev/cli/appium/real-devices.md
  docs/dev/cli/espresso-xcuitest.md
  docs/dev/cli/espresso-xcuitest/real-devices.md
  docs/dev/cli/espresso-xcuitest/virtual-devices.md
  docs/dev/cli/sauce-connect-proxy.md
  docs/mobile-apps/automated-testing/appium/real-devices.md
  docs/mobile-apps/faq.md
Labels: documentation

#359 More Native FW CLI changes
  docs/dev/cli/appium/real-devices.md
  docs/dev/cli/espresso-xcuitest.md
  docs/dev/cli/espresso-xcuitest/real-devices.md
  docs/dev/cli/espresso-xcuitest/virtual-devices.md
Labels: documentation

#360 Appium, Native FW, vUSB CLI
  docs/dev/cli/appium/real-devices.md
  docs/dev/cli/espresso-xcuitest.md
  docs/dev/cli/virtual-usb.md
Labels: documentation

#363 TestObject redirects
  docs/mobile-apps.md
  docs/mobile-apps/supported-devices.md
Labels: documentation

#364 supported devices minor change
  docs/mobile-apps/supported-devices.md
Labels: documentation

#365 Supported devices conflict fix
  docs/mobile-apps/supported-devices.md
Labels: bug, documentation

#366 Native FW badges
  docs/dev/cli/appium/real-devices.md
  docs/dev/cli/espresso-xcuitest/real-devices.md
  docs/mobile-apps/live-testing/live-mobile-app-testing.md
  sidebars.js
Labels: documentation

#369 Native FW CLI redirects to saucectl
  docs/dev/cli/espresso-xcuitest.md
  docs/dev/cli/espresso-xcuitest/real-devices.md
  docs/dev/cli/espresso-xcuitest/virtual-devices.md
Labels: documentation

#372 Native FW/saucectl, SC CLI
  docs/dev/cli/appium/real-devices.md
  docs/dev/cli/espresso-xcuitest.md
  docs/dev/cli/espresso-xcuitest/virtual-devices.md
  docs/dev/cli/sauce-connect-proxy.md
  docs/mobile-apps/automated-testing.md
  docs/mobile-apps/automated-testing/espresso-xcuitest.md
  docs/mobile-apps/automated-testing/espresso-xcuitest/virtual-devices.md
  docs/mobile-apps/automated-testing/ipa-files.md
Labels: documentation

#373 vUSB change (TCD-1529)
  docs/dev/cli/espresso-xcuitest.md
  docs/dev/cli/virtual-usb.md
Labels: bug, documentation

#371 updated index links
  src/pages/home-callouts.js
Labels: bug

#361 Deque Axe Integration Page
  docs/basics/integrations/deque.md
  sidebars.js
  src/css/fw-badge-override.css
Labels: documentation

#367 DON'T MERGE test config options
  docs/dev/cli/sauce-connect-proxy.md
  docs/dev/cli/test-configuration-options.md
  docs/mobile-apps/automated-testing/appium/real-devices.md
  sidebars.js
Labels: documentation

#385 common error messages
  docs/dev/cli/error-messages.md
  docs/dev/cli/test-configuration-options.md
  docs/mobile-apps/automated-testing/troubleshooting.md
  sidebars.js
Labels: documentation

#391 Headless and test config options
  docs/headless.md
  sidebars.js
Labels: bug, documentation

#393 App Storage and other CLI docs
  docs/dev/cli/test-configuration-options.md
  docs/dev/error-messages.md
  docs/dev/test-configuration-options.md
  docs/mobile-apps.md
  docs/mobile-apps/app-storage.md
  docs/mobile-apps/automated-testing/appium/real-devices.md
  docs/mobile-apps/virtual-usb.md
Labels: documentation

#394 Glossary, sidebars
  docs/dev/error-messages.md
  docs/dev/glossary.md
  docs/secure-connections/sauce-connect/environment-variables.md
  sidebars.js
Labels: documentation

#395 Glossary, app storage, error messages
  docs/dev/error-messages.md
  docs/dev/glossary.md
  docs/mobile-apps/faq.md
Labels: documentation

#396 Implemented Titus edits (1st round draft; awaiting other reviewers)
  docs/dev/test-configuration-options.md
Labels: documentation

#398 W3C caps draft
  docs/dev/cli/test-configuration-options.md
  docs/dev/cli/w3c-webdriver-capabilities.md
  docs/dev/error-messages.md
  docs/dev/glossary.md
  docs/mobile-apps/faq.md
  sidebars.js
  static/img/test-results/test-results-w3c.jpg
Labels: documentation

#399 platform config guide
  docs/basics/platform-configurator.md
  sidebars.js
Labels: documentation

#397 Added -d flag to gsutil to remove stale objects
  .github/workflows/deploy.yml
Labels: bug

#402 Modified sidebars for /dev
  docs/cli-format-proposal.md
  docs/dev/w3c-webdriver-capabilities.md
  sidebars.js
Labels: documentation

#407 Fixed Reference IA
  docs/dev/error-messages.md
  docs/dev/glossary.md
  docs/dev/test-configuration-options.md
  docs/dev/w3c-webdriver-capabilities.md
  docs/mobile-apps/faq.md
  sidebars.js
Labels: documentation

#408 Cleaned up Appium quick start
  docs/mobile-apps/automated-testing/appium.md
Labels: documentation

#409 Test Config Options - Titus Draft #2 changes
  docs/dev/test-configuration-options.md
Labels: documentation

#412 Fixed Reference IA, deprecated Appium-only caps page
  docs/appium-capabilities.md
  docs/dev/cli/appium/virtual-devices.md
  docs/dev/test-configuration-options.md
  docs/mobile-apps/automated-testing/appium/real-devices.md
  docs/mobile-apps/faq.md
  docs/mobile-apps/supported-devices.md
  sidebars.js
Labels: bug, documentation
