Repository saucelabs/sauce-docs, pull requests merged in 2021-11, with the labels that each got.

#846 rm -N (--no-proxy-caching)
  docs/api-testing/on-prem/how-to/set-dynamic-dates.md
  docs/secure-connections/sauce-connect/security-authentication.md
  static/img/api-fortress/2018/04/valueField.jpg
Labels: documentation

#848 Added banner to legacy API docs
  docs/api-testing/on-prem/bloodhound.md
  docs/api-testing/on-prem/io-components.md
  docs/api-testing/on-prem/postman/build-from-collections.md
  docs/api-testing/on-prem/quick-start.md
  docs/api-testing/on-prem/quick-start/build-from-spec.md
  docs/secure-connections/sauce-connect/proxy-tunnels.md
Labels: documentation

#851 SC Tunnel page > Starting/Stopping Tunnels section edits
  docs/secure-connections/sauce-connect/proxy-tunnels.md
  docs/visual/e2e-testing/supported-browsers.md
  docs/visual/faq.md
  sidebars.js
Labels: bug, documentation

#856 SC FAQ change for visual e2e test
  docs/secure-connections/sauce-connect/faq.md
  docs/visual/faq.md
Labels: bug, documentation

#857 SC Proxy Tunnels doc
  docs/visual/faq.md
Labels: documentation

#853 apifctl revisions
  docs/api-testing/apifctl-cicd-integration.md
  docs/api-testing/integrate-with-your-cicd.md
  docs/visual/faq.md
  sidebars.js
  static/img/api-fortress/2021/04/createHook.png
Labels: documentation

#859 apifctl edits per LS
  docs/api-testing/apifctl-cicd-integration.md
Labels: documentation

#760 API Testing | Mocking and Logger docs
  docs/api-testing/logger.md
  docs/api-testing/mocking.md
  docs/dev/glossary.md
  sidebars.js
  static/img/api-fortress/2021/09/logger.png
  static/img/api-fortress/2021/09/logger1.png
  static/img/api-fortress/2021/09/logger2.png
  static/img/api-fortress/2021/09/logger3.png
Labels: documentation, enhancement

#860 API Testing Quickstart edits
  docs/api-testing/quickstart.md
  static/img/api-fortress/2021/01/enterRequestURL2.png
  static/img/api-fortress/2021/01/generateTest.png
  static/img/api-fortress/2021/01/importSpec.png
  static/img/api-fortress/2021/01/importSpec2.png
  static/img/api-fortress/2021/01/importSpec3.png
  static/img/api-fortress/2021/01/newProject.png
Labels: documentation

#861 API Scheduler, Reports, Dashboard, Spec, Postman
  docs/api-testing/build-from-spec.md
  docs/api-testing/dashboard.md
  docs/api-testing/environments-vault-and-overrides-magic.md
  docs/api-testing/environments-vault-overrides.md
  docs/api-testing/importing-postman-collections.md
  docs/api-testing/sauce-connect.md
  docs/api-testing/schedule-a-test.md
  docs/api-testing/test-reports.md
  docs/api-testing/variables-flexible-environments.md
  docs/api-testing/vault.md
  sidebars.js
  static/img/api-fortress/2021/02/createSchedule.png
  static/img/api-fortress/2021/02/dashboardFilters.png
  static/img/api-fortress/2021/02/dashboardLogs.png
  static/img/api-fortress/2021/02/dashboardReport.png
  static/img/api-fortress/2021/02/exampleSchedule.png
  static/img/api-fortress/2021/02/metrics.png
  static/img/api-fortress/2021/02/metricsFilters.png
  static/img/api-fortress/2021/02/publishButton.png
  static/img/api-fortress/2021/02/published.png
  static/img/api-fortress/2021/02/scheduleConfirm.png
  static/img/api-fortress/2021/02/scheduleOptions.png
  static/img/api-fortress/2021/02/scheduleTab.png
  static/img/api-fortress/2021/02/schedules.png
  static/img/api-fortress/2021/02/unpublished.png
Labels: documentation

#858 API Composer and Components docs
  docs/api-testing/apifctl-cicd-integration.md
  docs/api-testing/composer.md
  docs/api-testing/composer/assertion-components.md
  docs/api-testing/composer/io-components.md
  docs/api-testing/composer/logical-components.md
  sidebars.js
  static/img/api-fortress/2020/09/assertionComponents.png
  static/img/api-fortress/2020/09/ioComponents.png
  static/img/api-fortress/2020/09/logicalComponents.png
  static/img/api-fortress/2020/11/basicAuth.png
  static/img/api-fortress/2020/11/compsAvail.jpg
  static/img/api-fortress/2020/11/compsAvail2.png
  static/img/api-fortress/2020/11/githubComponent.png
  static/img/api-fortress/2020/12/parseComponentUI.jpeg
  static/img/api-fortress/2020/12/parseComponentUI_results.png
  static/img/api-fortress/2020/12/parseComponentUI_test.png
  static/img/api-fortress/2020/12/parseComponentUI_variable.png
  static/img/api-fortress/2020/12/setvar.jpeg
  static/img/api-fortress/2020/12/setvarJava.jpeg
  static/img/api-fortress/2020/12/setvarObject.jpeg
  static/img/api-fortress/2020/12/tagNewtest.png
  static/img/api-fortress/2020/12/while.jpg
  static/img/api-fortress/2021/01/addComponent.png
  static/img/api-fortress/2021/01/codeView.png
  static/img/api-fortress/2021/01/deleteComponent.png
  static/img/api-fortress/2021/01/exportSnippet.png
  static/img/api-fortress/2021/01/inputSets.png
  static/img/api-fortress/2021/01/invokeSnippet.png
  static/img/api-fortress/2021/01/runTest.png
  static/img/api-fortress/2021/01/saveTest.png
  static/img/api-fortress/2021/01/transformComponent.png
  static/img/api-fortress/2021/01/unitView.png
  static/img/api-fortress/2021/01/visualView.png
  static/img/api-fortress/2021/04/hookURL.png
Labels: documentation

#862 apifctl edits per LS
  docs/api-testing/apifctl-cicd-integration.md
Labels: documentation

#863 API Mocking edits
  docs/api-testing/mocking.md
  sidebars.js
Labels: documentation

#864 API Mocking, Glossary edits
  docs/api-testing/mocking.md
  docs/dev/glossary.md
Labels: documentation

#865 Quickstart updates to align with UI updates
  docs/secure-connections/sauce-connect/quickstart.md
Labels: documentation

#866 Spec, Postman, Quickstart docs
  docs/api-testing/build-from-spec.md
  docs/api-testing/composer.md
  docs/api-testing/composer/logical-components.md
  docs/api-testing/importing-postman-collections.md
  docs/api-testing/quickstart.md
  docs/api-testing/schedule-a-test.md
  docs/api-testing/test-reports.md
  docs/api-testing/variables-flexible-environments.md
  docs/api-testing/vault.md
  static/img/api-fortress/2021/02/testCode.png
  static/img/api-fortress/2021/02/testVisual.png
  static/img/api-fortress/2021/04/companyVault.png
  static/img/api-fortress/2021/04/companyVault2.png
  static/img/api-fortress/2021/04/import.png
  static/img/api-fortress/2021/04/importFolder.png
  static/img/api-fortress/2021/04/importFolder2.png
  static/img/api-fortress/2021/04/projectVault.png
  static/img/api-fortress/2021/04/routesRendered.png
  static/img/api-fortress/2021/04/vault.png
Labels: documentation

#869 Revised webhook section
  docs/api-testing/logger.md
Labels: documentation

#870 Minor edits per LS to commands/options
  docs/api-testing/apifctl-cicd-integration.md
Labels: documentation

#872 SC quickstart fixes / add live test
  docs/secure-connections/sauce-connect/installation.md
  docs/secure-connections/sauce-connect/quickstart.md
  static/img/sauce-connect/configureAuth.png
  static/img/sauce-connect/tunnelsPage.png
Labels: documentation

#875 Logger formatting change
  docs/api-testing/logger.md
Labels: documentation

#876 Clarifications to Legacy API Testing doc navigation
  docs/api-testing/build-from-spec.md
  docs/api-testing/dashboard.md
  docs/api-testing/on-prem/quick-start.md
  docs/api-testing/schedule-a-test.md
  docs/api-testing/test-reports.md
  sidebars.js
  static/img/api-fortress/2021/02/assertions.png
  static/img/api-fortress/2021/02/fullReport.png
  static/img/api-fortress/2021/02/generalDetails.png
  static/img/api-fortress/2021/02/requestComponent.png
  static/img/api-fortress/2021/02/sessionDetails.png
  static/img/api-fortress/2021/02/versions.png
Labels: documentation

#871 Edits to Dashboard, Spec, Env, Vault, Var, Test Reports
  docs/api-testing/dashboard.md
  docs/api-testing/environments-vault-overrides.md
  docs/api-testing/environments.md
  docs/api-testing/schedule-a-test.md
  docs/api-testing/test-reports.md
  docs/api-testing/variables-environment-overrides.md
  docs/api-testing/variables-flexible-environments.md
  docs/api-testing/vault.md
  sidebars.js
Labels: documentation

#877 Mocking, apifctl, Logger
  docs/api-testing/apifctl-cicd-integration.md
  docs/api-testing/logger.md
  docs/api-testing/mocking.md
Labels: documentation

#878 SC CLI changes
  docs/dev/cli/sauce-connect-proxy.md
  docs/dev/glossary.md
Labels: documentation

#879 SC quickstart and troubleshooting
  docs/dev/cli/sauce-connect-proxy.md
  docs/secure-connections/sauce-connect/installation.md
  docs/secure-connections/sauce-connect/quickstart.md
  docs/secure-connections/sauce-connect/troubleshooting.md
Labels: documentation

#881 [TCD-2120] Remove Device Icons
  docs/mobile-apps/supported-devices.md
Labels: documentation

#888 SC Proxy basic setup consolidation
  docs/dev/cli/sauce-connect-proxy.md
  docs/dev/glossary.md
  docs/secure-connections.md
  docs/secure-connections/sauce-connect.md
  docs/secure-connections/sauce-connect/quickstart.md
  docs/secure-connections/sauce-connect/setup-configuration.md
  docs/secure-connections/sauce-connect/setup-configuration/basic-setup.md
  sidebars.js
  static/img/sauce-connect/scp-download.png
  static/img/sauce-connect/scp-yaml.png
Labels: documentation

#887 Selenium 4 edits/additions
  docs/web-apps/automated-testing/selenium/selenium4.md
Labels: documentation

#891 API Dashboard, Env, Variables, Composer, Scheduler
  docs/api-testing/composer.md
  docs/api-testing/dashboard.md
  docs/api-testing/environments.md
  docs/api-testing/schedule-a-test.md
  docs/api-testing/variables-environment-overrides.md
  docs/api-testing/vault.md
  static/img/api-fortress/2021/02/scheduleIcons.png
Labels: documentation

#885 apifctl fixes
  docs/api-testing/apifctl-cicd-integration.md
Labels: documentation

#892 API/SC integration, quickstart, env var, test reports
  docs/api-testing/environments.md
  docs/api-testing/quickstart.md
  docs/api-testing/sauce-connect.md
  docs/api-testing/test-reports.md
  docs/api-testing/variables-environment-overrides.md
  docs/secure-connections/sauce-connect/quickstart.md
  static/img/api-fortress/2021/02/sessionDetails.png
  static/img/api-fortress/2021/09/sauceconnect-folders.png
  static/img/api-fortress/2021/09/sauceconnect-nav1.png
Labels: documentation

#894 Aligned SC CLI with --help output
  docs/dev/cli/sauce-connect-proxy.md
  docs/secure-connections/sauce-connect/proxy-tunnels.md
Labels: documentation

#895 removed TO references
  docs/dev/test-configuration-options.md
  docs/secure-connections/sauce-connect/faq.md
  docs/secure-connections/sauce-connect/setup-configuration/legacy-tunnels.md
  docs/secure-connections/sauce-connect/setup-configuration/specialized-environments.md
  sidebars.js
Labels: documentation

#889 YAML config, CLI, basic setup
  docs/dev/cli/sauce-connect-proxy.md
  docs/secure-connections/sauce-connect/setup-configuration/basic-setup.md
  docs/secure-connections/sauce-connect/setup-configuration/yaml-config.md
  sidebars.js
Labels: documentation

#896 SC CLI, env variables, yaml config doc
  docs/api-testing/apifctl-cicd-integration.md
  docs/basics/sso/setting-up-single-sign-on.md
  docs/dev/cli/sauce-connect-proxy.md
  docs/dev/cli/virtual-usb/connect-session.md
  docs/dev/cli/virtual-usb/delete-session.md
  docs/dev/cli/virtual-usb/find-sessionid.md
  docs/dev/cli/virtual-usb/start-session.md
  docs/dev/w3c-webdriver-capabilities.md
  docs/mobile-apps/features/virtual-usb.md
  docs/secure-connections/ipsec-vpn.md
  docs/secure-connections/sauce-connect/installation.md
  docs/secure-connections/sauce-connect/proxy-tunnels.md
  docs/secure-connections/sauce-connect/setup-configuration/additional-proxies.md
  docs/secure-connections/sauce-connect/setup-configuration/high-availability.md
  docs/secure-connections/sauce-connect/setup-configuration/specialized-environments.md
  docs/secure-connections/sauce-connect/setup-configuration/yaml-config.md
Labels: documentation

#898 Added API Testing to specialized SC setups
  docs/secure-connections/sauce-connect/setup-configuration/additional-proxies.md
  docs/secure-connections/sauce-connect/setup-configuration/basic-setup.md
  docs/secure-connections/sauce-connect/setup-configuration/ci-cd-environments.md
  docs/secure-connections/sauce-connect/setup-configuration/environment-variables.md
  docs/secure-connections/sauce-connect/setup-configuration/high-availability.md
  docs/secure-connections/sauce-connect/setup-configuration/specialized-environments.md
  docs/secure-connections/sauce-connect/setup-configuration/yaml-config.md
Labels: documentation

#899 Removed Cybervillains certificate references
  docs/dev/cli/sauce-connect-proxy.md
  docs/secure-connections/sauce-connect/proxy-tunnels.md
  docs/secure-connections/sauce-connect/security-authentication.md
  docs/testrunner-toolkit/configuration.md
Labels: documentation

#904 Edits to Set Variable Component section
  docs/api-testing/variables-environment-overrides.md
Labels: documentation

#907 Secure Connections home, SC home, SC quickstart
  docs/api-testing/sauce-connect.md
  docs/secure-connections.md
  docs/secure-connections/sauce-connect.md
  docs/secure-connections/sauce-connect/proxy-tunnels.md
  docs/secure-connections/sauce-connect/quickstart.md
  docs/secure-connections/sauce-connect/setup-configuration/basic-setup.md
Labels: documentation

#909 SC performance/traffic config section
  docs/dev/glossary.md
  docs/secure-connections/sauce-connect/proxy-tunnels.md
Labels: documentation

#914 SC env var, tunnels, HA docs
  docs/dev/cli/sauce-connect-proxy.md
  docs/secure-connections/sauce-connect/proxy-tunnels.md
  docs/secure-connections/sauce-connect/setup-configuration/environment-variables.md
  docs/secure-connections/sauce-connect/setup-configuration/high-availability.md
Labels: documentation

#915 CICD, Tunnels, HA docs
  docs/secure-connections.md
  docs/secure-connections/sauce-connect/proxy-tunnels.md
  docs/secure-connections/sauce-connect/setup-configuration/additional-proxies.md
  docs/secure-connections/sauce-connect/setup-configuration/ci-cd-integration.md
  docs/secure-connections/sauce-connect/setup-configuration/high-availability.md
  sidebars.js
Labels: documentation

#918 API Testing components docs/formatting
  docs/api-testing/composer.md
  docs/api-testing/composer/logical-components.md
  static/img/api-fortress/2018/05/Screen-Shot-2018-05-24-at-1.46.41-PM.png
  static/img/api-fortress/2018/05/Screen-Shot-2018-05-24-at-1.47.22-PM.png
  static/img/api-fortress/2018/05/Screen-Shot-2018-05-24-at-1.48.01-PM.png
  static/img/api-fortress/2018/05/Screen-Shot-2018-05-24-at-1.48.28-PM.png
  static/img/api-fortress/2018/05/Screen-Shot-2018-05-24-at-1.49.16-PM.png
  static/img/api-fortress/2018/05/Screen-Shot-2018-05-24-at-1.51.48-PM.png
  static/img/api-fortress/2018/05/Screen-Shot-2018-05-24-at-1.51.59-PM.png
  static/img/api-fortress/2018/05/Screen-Shot-2018-05-24-at-2.28.58-PM.png
  static/img/api-fortress/2018/05/Screen-Shot-2018-05-24-at-2.29.09-PM.png
  static/img/api-fortress/2018/05/Screen-Shot-2018-05-24-at-2.31.17-PM.png
  static/img/api-fortress/2018/05/Screen-Shot-2018-05-24-at-2.43.53-PM.png
  static/img/api-fortress/2020/12/parseComponentUI.jpeg
  static/img/api-fortress/2020/12/parseComponentUI_results.png
  static/img/api-fortress/2020/12/parseComponentUI_test.png
  static/img/api-fortress/2020/12/parseComponentUI_variable.png
  static/img/api-fortress/2020/12/projDashTag.jpg
  static/img/api-fortress/2020/12/projDashTag.png
  static/img/api-fortress/2020/12/tagComposer.jpg
  static/img/api-fortress/2020/12/tagComposer.png
  static/img/api-fortress/2020/12/tagNewtest.png
  static/img/api-fortress/2020/12/testsTag.png
Labels: documentation

#922 Selenium code example fixes, formatting
  docs/dev/w3c-webdriver-capabilities.md
  docs/web-apps/automated-testing/selenium.md
Labels: documentation

#923 API Testing reorg/clarifications
  docs/api-testing.md
  docs/api-testing/apifctl-cicd-integration.md
  docs/api-testing/build-from-spec.md
  docs/api-testing/composer.md
  docs/api-testing/dashboard.md
  docs/api-testing/import-export-tests.md
  docs/api-testing/import-postman-collection.md
  docs/api-testing/metrics-logs.md
  docs/api-testing/quickstart.md
  docs/api-testing/sauce-connect.md
  docs/api-testing/vault.md
  sidebars.js
  static/img/api-fortress/2021/02/dash-1.1.png
  static/img/api-fortress/2021/02/dashboardLogs.png
Labels: documentation
