Repository saucelabs/sauce-docs, pull requests merged in 2021-08, with the labels that each got.

#569 Link fixes
  docs/appium-capabilities.md
  docs/mobile-apps.md
  docs/mobile-apps/automated-testing/appium/real-devices.md
  docs/mobile-apps/automated-testing/espresso-xcuitest/real-devices.md
  docs/mobile-apps/virtual-usb.md
  docs/secure-connections/sauce-connect/security-authentication.md
Labels: documentation

#495 TCD-1564: Announcement Bar
  docusaurus.config.js
  src/css/announcement-bar.css
  src/css/custom.css
  static/img/saucebot-announcementbar.png
Labels: documentation, enhancement

#573 rm saucebot image from banner
  docusaurus.config.js
  src/css/announcement-bar.css
  src/css/custom.css
Labels: documentation, enhancement

#583 image injection video/text
  docs/mobile-apps/features.md
Labels: documentation

#584 Appium and Test Config Options
  docs/appium-capabilities.md
  docs/dev/test-configuration-options.md
  docs/mobile-apps/automated-testing/appium/real-devices.md
  docs/mobile-apps/features.md
Labels: bug, documentation

#571 [TCD-1749] Added cicd doc for api-testing mark3
  docs/api-testing/mark3/quick-start/integrate-with-your-cicd.md
  sidebars.js
Labels: documentation

#588 [TCD-1757] Updated Footer Links
  docusaurus.config.js
  src/theme/Footer/index.js
Labels: enhancement

#601 reversed button hover colors (custom.css)
  src/css/custom.css
Labels: documentation, enhancement

#603 SC CLI - applied condensed line spacing
  docs/dev/cli.md
  docs/dev/cli/sauce-connect-proxy.md
Labels: documentation

#604 applied condensed line spacing
  docs/dev/cli/virtual-usb/connect-session.md
  docs/dev/cli/virtual-usb/delete-session.md
  docs/dev/cli/virtual-usb/disconnect-session.md
  docs/dev/cli/virtual-usb/find-sessionid.md
  docs/dev/cli/virtual-usb/start-server.md
  docs/dev/cli/virtual-usb/start-session.md
Labels: documentation

#623 announcementBar changes: bg color and "NEW" badge
  docusaurus.config.js
  src/css/announcement-bar.css
  src/css/custom.css
Labels: documentation, enhancement

#624 W3C caps doc improvements
  docs/dev/w3c-webdriver-capabilities.md
Labels: documentation

#625 Test Config Options edits for clarity, style, brevity
  docs/dev/test-configuration-options.md
Labels: documentation

#626 Appium caps
  docs/dev/test-configuration-options.md
  src/css/custom.css
Labels: documentation

#627 Test Features
  docs/dev/test-configuration-options.md
  docs/mobile-apps/features.md
  docs/mobile-apps/virtual-usb.md
Labels: documentation

#629 clean up image injection
  docs/mobile-apps/features.md
Labels: documentation

#630 sauce connect, headless, basics
  docs/basics/acct-team-mgmt/managing-user-info.md
  docs/headless.md
  docs/secure-connections/sauce-connect/changelog.md
  docs/secure-connections/sauce-connect/installation.md
  docs/secure-connections/sauce-connect/security-authentication.md
  docs/secure-connections/sauce-connect/setup-configuration/basic-setup.md
  docs/secure-connections/sauce-connect/setup-configuration/ci-cd-environments.md
  docs/secure-connections/sauce-connect/setup-configuration/legacy-tunnels.md
  docs/secure-connections/sauce-connect/setup-configuration/specialized-environments.md
  docs/secure-connections/sauce-connect/system-requirements.md
  docs/secure-connections/sauce-connect/troubleshooting.md
Labels: documentation

#634 Image injection > automated testing > code sample
  docs/mobile-apps/features.md
Labels: bug, documentation

#653 Rearranged mobile testing features, sidebars
  docs/basics/acct-team-mgmt/private-device-mgmt.md
  docs/dev/cli/virtual-usb.md
  docs/dev/cli/virtual-usb/connect-session.md
  docs/dev/cli/virtual-usb/delete-session.md
  docs/dev/cli/virtual-usb/disconnect-session.md
  docs/dev/cli/virtual-usb/start-server.md
  docs/dev/cli/virtual-usb/start-session.md
  docs/dev/test-configuration-options.md
  docs/mobile-apps/features.md
  docs/mobile-apps/features/biometric-authentication.md
  docs/mobile-apps/features/camera-image-injection.md
  docs/mobile-apps/features/gestures.md
  docs/mobile-apps/features/virtual-usb.md
  docs/mobile-apps/live-testing/live-mobile-app-testing.md
  sidebars.js
Labels: documentation

#654 fixed incorrect written instances of 'quickstart'
  docs/api-testing.md
  docs/api-testing/mark2/quick-start/easy-monitoring.md
  docs/visual.md
  sidebars.js
Labels: bug, documentation

#655 Api sauceschool
  docs/api-testing.md
  docs/api-testing/mark2/quick-start/composer.md
  docs/api-testing/mark3/quick-start/composer.md
Labels: documentation

#656 [TCD-1892] Added "stop_urls" for APIFM2 config
  .docsearch/config.json
Labels: bug, documentation

#658 [TCD-1792] Integrate Segment for JS
  docusaurus.config.js
Labels: enhancement

#663 APIF IA, sidebars changes
  docs/api-testing.md
  docs/api-testing/mark2/quick-start.md
  docs/api-testing/mark3/quick-start.md
  docs/api-testing/mark3/quick-start/composer.md
  docs/api-testing/mark3/quick-start/flexible-variables-for-flexible-environments.md
  docs/api-testing/mark3/quick-start/integrate-with-your-cicd.md
  docs/api-testing/mark3/quick-start/the-vault.md
  sidebars.js
Labels: documentation, enhancement

#664 Added What You'll Need CTA
  docs/basics/data-center-endpoints/data-center-endpoints.md
  docs/basics/environment-variables.md
  docs/basics/integrations/deque.md
  docs/basics/integrations/jira.md
  docs/basics/test-config-annotation/test-annotation.md
  docs/ci/jenkins.md
  docs/dev/api.md
  docs/dev/api/jobs.md
  docs/dev/api/storage.md
  docs/dev/test-configuration-options.md
  docs/dev/w3c-webdriver-capabilities.md
  docs/insights/debug.md
  docs/mobile-apps/app-storage.md
  docs/mobile-apps/automated-testing.md
  docs/mobile-apps/automated-testing/appium.md
  docs/mobile-apps/automated-testing/appium/real-devices.md
  docs/mobile-apps/automated-testing/espresso-xcuitest/real-devices.md
  docs/mobile-apps/live-testing/live-mobile-app-testing.md
  docs/sauce-basics.md
  docs/testrunner-toolkit.md
  docs/testrunner-toolkit/installation.md
  docs/web-apps/automated-testing/selenium.md
  docs/web-apps/live-testing/live-cross-browser-testing.md
Labels: documentation
