Repository saucelabs/sauce-docs, pull requests merged in 2021-09, with the labels that each got.

#665 Re-run: Added What You'll Need CTA round2
  docs/basics/quickstarts.md
  docs/dev/api/connect.md
  docs/mobile-apps/automated-testing/appium/appium-migration.md
  docs/mobile-apps/automated-testing/appium/virtual-devices.md
  docs/mobile-apps/automated-testing/espresso-xcuitest.md
  docs/mobile-apps/features/biometric-authentication.md
  docs/mobile-apps/features/camera-image-injection.md
  docs/mobile-apps/supported-devices.md
  docs/performance/transitions.md
  docs/secure-connections/sauce-connect.md
  docs/secure-connections/sauce-connect/installation.md
  docs/secure-connections/sauce-connect/setup-configuration/setup-configuration.md
  docs/test-results/test-status.md
  docs/test-results/viewing-test-results.md
  docs/web-apps/automated-testing/selenium/pre-run-executables.md
Labels: documentation

#671 What You'll Need CTA round3
  docs/basics/integrations/deque.md
  docs/basics/quickstarts.md
  docs/dev/test-configuration-options.md
  docs/mobile-apps/automated-testing.md
  docs/mobile-apps/automated-testing/appium.md
  docs/mobile-apps/features/biometric-authentication.md
  docs/mobile-apps/features/camera-image-injection.md
  docs/mobile-apps/features/gestures.md
  docs/mobile-apps/features/virtual-usb.md
  docs/mobile-apps/live-testing/live-mobile-app-testing.md
  docs/mobile-apps/supported-devices.md
  docs/secure-connections/sauce-connect.md
  docs/secure-connections/sauce-connect/installation.md
  docs/secure-connections/sauce-connect/setup-configuration/setup-configuration.md
  docs/test-results/test-status.md
  docs/test-results/viewing-test-results.md
  docs/web-apps/automated-testing/puppeteer.md
  docs/web-apps/automated-testing/selenium.md
  docs/web-apps/automated-testing/selenium/pre-run-executables.md
  docs/web-apps/automated-testing/testcafe.md
  docs/web-apps/live-testing/live-cross-browser-testing.md
Labels: documentation

#676 SC CLI 4.7.0 edits
  docs/dev/cli/sauce-connect-proxy.md
  sidebars.js
Labels: documentation

#678 [TCD-1757] Update custom.css and footer styles
  cypress.json
  src/css/custom.css
  src/css/footer-styles.css
  src/theme/Footer/index.js
  tests/cypress/integration/footer.test.js
Labels: bug

#683 minor changes to troubleshooting and CLI
  docs/dev/cli/sauce-connect-proxy.md
  docs/secure-connections/sauce-connect/troubleshooting.md
Labels: documentation

#686 rm 'Sauce Labs app/Sauce Labs dashboard' references (TCD-1849)
  docs/basics/integrations/jira.md
  docs/ci/jenkins.md
  docs/dev/api.md
  docs/dev/error-messages.md
  docs/dev/glossary.md
  docs/dev/test-configuration-options.md
  docs/insights/debug.md
  docs/insights/history.md
  docs/insights/scope.md
  docs/mobile-apps/automated-testing/appium/appium-migration.md
  docs/mobile-apps/automated-testing/appium/quickstart.md
  docs/mobile-apps/automated-testing/appium/real-devices.md
  docs/mobile-apps/automated-testing/espresso-xcuitest.md
  docs/performance.md
  docs/performance/analyze.md
  docs/performance/motion.md
  docs/performance/transitions.md
  docs/secure-connections/sauce-connect/proxy-tunnels.md
  docs/test-results/test-status.md
  docs/testrunner-toolkit/configuration/espresso.md
  docs/testrunner-toolkit/configuration/xcuitest.md
  docs/testrunner-toolkit/installation.md
  docs/web-apps/automated-testing/cypress/quickstart.md
  docs/web-apps/automated-testing/playwright/quickstart.md
  docs/web-apps/automated-testing/puppeteer/quickstart.md
  docs/web-apps/automated-testing/testcafe/quickstart.md
Labels: bug, documentation

#690 Fixed NOTE formatting throughout docs (TCD-1934)
  docs/basics/acct-team-mgmt/org-settings.md
  docs/dev/cli/espresso-xcuitest/yaml-config.md
  docs/dev/cli/virtual-usb/disconnect-session.md
  docs/dev/test-configuration-options.md
  docs/dev/w3c-webdriver-capabilities.md
  docs/headless.md
  docs/insights/scope.md
  docs/mobile-apps/automated-testing/appium/using-appium.md
  docs/mobile-apps/creating-ipa-files.md
  docs/mobile-apps/features/virtual-usb.md
  docs/mobile-apps/live-testing/live-mobile-app-testing.md
  docs/secure-connections/sauce-connect/setup-configuration/additional-proxies.md
  docs/visual/acct-team-mgmt.md
  docs/visual/component-testing/testing-interactions.md
  docs/visual/e2e-testing/webdriver-integration.md
  docs/web-apps/live-testing/live-cross-browser-testing.md
Labels: documentation

#691 Added SC version lifecycle info
  docs/dev/cli/sauce-connect-proxy.md
  docs/secure-connections/sauce-connect/installation.md
Labels: documentation

#695 [TCD-1922] Adjust footer css
  src/css/footer-styles.css
Labels: bug

#697 Applied CLI Formatting to Test Configuration Options (TCD-1939)
  docs/dev/test-configuration-options.md
Labels: documentation

#707 Added Linux download instructions, converted 1st table from .jsx-->static
  docs/secure-connections/sauce-connect/installation.md
Labels: documentation

#708 Added link to 4.7.0 changelog and a temp note about --doctor flag
  docs/secure-connections/sauce-connect/installation.md
  docs/secure-connections/sauce-connect/troubleshooting.md
Labels: documentation

#709 Update changelog, logfile troubleshooting
  docs/secure-connections/sauce-connect/changelog.md
  docs/secure-connections/sauce-connect/troubleshooting.md
Labels: bug, documentation

#710 Visual E2E CLI, sidebars, component/e2e testing sections edited for parallel structure
  docs/dev/cli.md
  docs/dev/cli/sauce-connect-proxy.md
  docs/dev/test-configuration-options.md
  docs/visual.md
  docs/visual/component-testing/animations.md
  docs/visual/component-testing/integrations/continuous-integration.md
  docs/visual/component-testing/integrations/sauce-labs.md
  docs/visual/component-testing/setup.md
  docs/visual/component-testing/storybook-interactions-testing.md
  docs/visual/component-testing/supported-browsers.md
  docs/visual/component-testing/testing-interactions.md
  docs/visual/component-testing/workflow/change-details.md
  docs/visual/css-animations.md
  docs/visual/e2e-testing/animations.md
  docs/visual/e2e-testing/commands.md
  docs/visual/e2e-testing/integrations/continuous-integration.md
  docs/visual/e2e-testing/options.md
  docs/visual/e2e-testing/setup.md
  docs/visual/e2e-testing/supported-browsers.md
  docs/visual/e2e-testing/visual-e2e-cli.md
  docs/visual/e2e-testing/workflow/change-details.md
  docs/visual/e2e-testing/workflow/review-workflow.md
  docs/visual/notifications.md
  sidebars.js
Labels: documentation

#714 Minor changes to mark3 doc, sidebars
  docs/api-testing/mark3/quick-start/environments-vault-and-overrides-magic.md
  docs/api-testing/mark3/quick-start/flexible-variables-for-flexible-environments.md
  docs/api-testing/mark3/quick-start/importing-postman-collections.md
  docs/api-testing/mark3/quick-start/the-vault.md
  sidebars.js
Labels: documentation

#717 fixed merge markers and visual commands/options
  docs/dev/cli.md
  docs/dev/test-configuration-options.md
  docs/mobile-apps/automated-testing/appium/using-appium.md
  docs/mobile-apps/creating-ipa-files.md
  docs/mobile-apps/features/virtual-usb.md
  docs/performance/transitions.md
  docs/secure-connections/sauce-connect/setup-configuration/additional-proxies.md
  docs/visual.md
  docs/visual/acct-team-mgmt.md
  docs/visual/e2e-testing/commands-options.md
  docs/visual/e2e-testing/integrations/continuous-integration.md
  docs/visual/e2e-testing/setup.md
  docs/visual/e2e-testing/workflow/baseline-branch.md
  sidebars.js
Labels: bug, documentation

#727 fixed visual commands and options
  docs/dev/cli.md
  docs/dev/test-configuration-options.md
  docs/visual.md
  docs/visual/e2e-testing/integrations/continuous-integration.md
  docs/visual/e2e-testing/setup.md
  docs/visual/e2e-testing/workflow/baseline-branch.md
Labels: documentation

#731 E2E code example page, plus unresolved changes from PR#686
  docs/basics/acct-team-mgmt/adding-deactivating-users.md
  docs/basics/acct-team-mgmt/adding-deleting-teams.md
  docs/basics/acct-team-mgmt/assigning-removing-users-teams.md
  docs/basics/acct-team-mgmt/managing-subscription.md
  docs/basics/acct-team-mgmt/managing-user-info.md
  docs/basics/acct-team-mgmt/org-settings.md
  docs/basics/acct-team-mgmt/plan-details.md
  docs/basics/acct-team-mgmt/private-device-mgmt.md
  docs/basics/acct-team-mgmt/updating-billing.md
  docs/basics/acct-team-mgmt/viewing-exporting-usage-data.md
  docs/basics/data-center-endpoints/aust-early-access.md
  docs/dev/glossary.md
  docs/mobile-apps/features/camera-image-injection.md
  docs/mobile-apps/live-testing/live-mobile-app-testing.md
  docs/performance/analyze.md
  docs/secure-connections/ipsec-vpn.md
  docs/secure-connections/sauce-connect/proxy-tunnels.md
  docs/secure-connections/sauce-connect/setup-configuration/specialized-environments.md
  docs/secure-connections/sauce-connect/troubleshooting.md
  docs/test-results/archived-test-results.md
  docs/test-results/managing-test-results.md
  docs/test-results/sharing-test-results.md
  docs/test-results/test-status.md
  docs/test-results/viewing-test-results.md
  docs/testrunner-toolkit/configuration/xcuitest.md
  docs/testrunner-toolkit/saucectl.md
  docs/visual/e2e-testing/code-examples.md
  docs/web-apps/live-testing/live-cross-browser-testing.md
Labels: documentation

#732 Changes to Basic setup, setup/config overview
  docs/secure-connections/sauce-connect/setup-configuration/basic-setup.md
  docs/secure-connections/sauce-connect/setup-configuration/setup-configuration.md
Labels: documentation

#733 SC Linux installation
  docs/secure-connections/sauce-connect/installation.md
Labels: documentation

#738 Installation doc - added 4.6.5 link
  docs/secure-connections/sauce-connect/installation.md
Labels: documentation
