Repository saucelabs/sauce-docs, pull requests merged in 2021-10, with the labels that each got.

#748 Selenium doc style updates to prep for Selenium 4 release
  docs/secure-connections/sauce-connect/system-requirements.md
  docs/web-apps/automated-testing/selenium.md
Labels: documentation

#749 switched sc and ipsec sections
  docs/secure-connections.md
  docs/web-apps/automated-testing/selenium.md
Labels: documentation

#747 Updating SC setup docs
  docs/secure-connections/sauce-connect/setup-configuration.md
  docs/secure-connections/sauce-connect/setup-configuration/specialized-environments.md
Labels: documentation

#753 Added 4.7.0 windows note
  docs/secure-connections/sauce-connect/installation.md
Labels: documentation

#755 Added new Quickstart doc
  docs/secure-connections/sauce-connect/quickstart.md
  sidebars.js
  static/img/sauce-connect/sauceconnect-tunnelstop-ui.png
  static/img/sauce-connect/sauceconnect-tunnelsuccess-UI.png
  static/img/sauce-connect/sauceconnect-tunnelsuccess-cli.png
Labels: documentation, enhancement

#765 added description field
  docs/dev/glossary.md
Labels: bug, documentation

#773 Changed 'latest version' link, cleaned up Download table
  docs/secure-connections/sauce-connect/changelog.md
  docs/secure-connections/sauce-connect/installation.md
  static/img/sauce-connect/sc-download.png
Labels: bug, documentation

#775 Minor edits to Security Auth doc
  docs/secure-connections/sauce-connect/installation.md
  docs/secure-connections/sauce-connect/security-authentication.md
Labels: documentation

#794 Edits to mark3/quickstart per Patrick
  docs/api-testing/mark3/quick-start.md
Labels: documentation

#784 Selenium 4 migration guide (work in progress)
  docs/dev/w3c-webdriver-capabilities.md
  docs/web-apps/automated-testing/selenium/selenium4.md
  sidebars.js
Labels: documentation, enhancement

#796 added a bunch of code examples to from demo repos
  docs/web-apps/automated-testing/selenium/selenium4.md
Labels: documentation, enhancement

#739 Added Azure to SC System Requirements doc
  docs/secure-connections/sauce-connect/system-requirements.md
Labels: documentation

#806 Minor edits to API/SC integration
  docs/api-testing/mark3/sauce-connect.md
Labels: bug, documentation

#821 Added Banner re: Screener-->Sauce Docs migration
  docs/visual.md
  docs/visual/component-testing/setup.md
  docs/visual/e2e-testing/setup.md
Labels: documentation, enhancement

#824 Removed /mark3 from API Testing URLs
  docs/api-testing.md
  docs/api-testing/build-from-spec.md
  docs/api-testing/composer.md
  docs/api-testing/dashboard.md
  docs/api-testing/environments-vault-and-overrides-magic.md
  docs/api-testing/flexible-variables-for-flexible-environments.md
  docs/api-testing/importing-postman-collections.md
  docs/api-testing/integrate-with-your-cicd.md
  docs/api-testing/quickstart.md
  docs/api-testing/sauce-connect.md
  docs/api-testing/schedule-a-test.md
  docs/api-testing/test-reports.md
  docs/api-testing/the-vault.md
  sidebars.js
Labels: documentation, enhancement
