Repository saucelabs/sauce-docs, pull requests merged in 2021-12, with the labels that each got.

#930 API Testing reorg/consolidation
  docs/api-testing/composer.md
  docs/api-testing/composer/io-components.md
  docs/api-testing/composer/logical-components.md
  docs/api-testing/composer/other-components.md
  sidebars.js
  static/img/api-fortress/2020/09/addComponentView.png
  static/img/api-fortress/2020/09/editTest.png
  static/img/api-fortress/2020/09/logicalComponents.png
  static/img/api-fortress/2020/09/otherComponents.png
  static/img/api-fortress/2020/11/authBasic.png
  static/img/api-fortress/2020/11/authConfig.png
  static/img/api-fortress/2020/11/authHeader.png
  static/img/api-fortress/2020/11/compsAvail2.png
  static/img/api-fortress/2020/11/editComponent1.png
  static/img/api-fortress/2020/11/editComponent2.png
  static/img/api-fortress/2020/11/editComponent3.png
  static/img/api-fortress/2020/11/githubComponent.png
  static/img/api-fortress/2020/11/ioAuth.png
  static/img/api-fortress/2020/11/ioAuth2.png
  static/img/api-fortress/2020/11/ioConfig.png
  static/img/api-fortress/2020/11/ioConfig2.png
  static/img/api-fortress/2020/11/ioHeader.png
  static/img/api-fortress/2020/11/ioHeader2.png
  static/img/api-fortress/2020/11/postBody.png
  static/img/api-fortress/2020/11/postBody1.png
  static/img/api-fortress/2020/11/postParam.png
  static/img/api-fortress/2020/11/postParam1.png
  static/img/api-fortress/2021/01/addComponent.png
  static/img/api-fortress/2021/01/addRequest.png
  static/img/api-fortress/2021/01/createTest.png
Labels: documentation

#920 SC FAQ addition
  docs/api-testing/composer/logical-components.md
  docs/secure-connections/sauce-connect/faq.md
Labels: documentation

#931 API Testing email notifications
  docs/api-testing/composer.md
  docs/api-testing/composer/other-components.md
  docs/api-testing/importing-postman-collections.md
  docs/api-testing/metrics-logs.md
  docs/api-testing/quickstart.md
  static/img/api-fortress/2018/05/Screen-Shot-2018-05-24-at-1.21.40-PM.png
  static/img/api-fortress/2018/05/component.png
  static/img/api-fortress/2019/11/Screen-Shot-2019-11-11-at-11.21.50-AM.png
  static/img/api-fortress/2019/11/Screen-Shot-2019-11-11-at-11.22.02-AM.png
  static/img/api-fortress/2019/11/Screen-Shot-2019-11-11-at-11.33.57-AM.png
  static/img/api-fortress/2020/07/Screen-Shot-2020-07-07-at-12.56.25-PM.png
  static/img/api-fortress/2020/07/Screen-Shot-2020-07-07-at-12.59.24-PM.png
Labels: documentation

#939 Visual E2E Project setup
  docs/visual/e2e-testing/setup.md
Labels: documentation

#943 Converted Component Testing Setup doc to Quickstart
  docs/basics/environment-variables.md
  docs/visual.md
  docs/visual/component-testing/quickstart.md
  docs/visual/component-testing/setup.md
  docs/visual/e2e-testing/quickstart.md
  sidebars.js
  static/img/visual/e2e-quickstart-accept.png
  static/img/visual/e2e-quickstart-all-projects.png
  static/img/visual/e2e-quickstart-changed-state.png
  static/img/visual/e2e-quickstart-changed-states.png
  static/img/visual/e2e-quickstart-enabledebugging.png
  static/img/visual/e2e-quickstart-new-accept.png
  static/img/visual/e2e-quickstart-success.png
  static/img/visual/e2e-quickstart-view-logs.png
  static/img/visual/e2e-quickstart-view-on-sauce.png
Labels: documentation

#911 Added SC Docker container info
  docs/secure-connections/sauce-connect/installation.md
  docs/secure-connections/sauce-connect/quickstart.md
  docs/secure-connections/sauce-connect/setup-configuration/specialized-environments.md
  docs/secure-connections/sauce-connect/system-requirements.md
Labels: documentation

#932 API Expressions
  docs/api-testing/composer/logical-components.md
  static/img/api-fortress/2020/13/assertEquals.png
  static/img/api-fortress/2020/13/equals-300x132.png
Labels: documentation

#947 Storybook quickstart
  docs/visual.md
  docs/visual/component-testing/quickstart.md
  docs/visual/component-testing/setup.md
  sidebars.js
Labels: documentation

#948 Storybook static testing
  docs/visual/component-testing/setup.md
  docs/visual/component-testing/storybook-static.md
  sidebars.js
Labels: documentation

#921 W3C changes
  docs/dev/w3c-webdriver-capabilities.md
  static/img/dev/w3c-compability.png
  static/img/test-results/test-results-w3c.jpg
Labels: documentation

#952 Component testing
  docs/visual/component-testing/setup.md
  docs/visual/component-testing/storybook-static.md
Labels: documentation

#953 Visual Testing FAQ addition
  docs/visual/faq.md
Labels: documentation

#954 Static Storybook doc changes
  docs/visual/component-testing/setup.md
  docs/visual/component-testing/storybook-static.md
Labels: documentation

#957 Visual E2E consolidation
  docs/visual/component-testing/setup.md
  docs/visual/e2e-testing/commands-options.md
  docs/visual/e2e-testing/quickstart.md
  docs/visual/e2e-testing/setup.md
  docs/visual/e2e-testing/workflow/baseline-branch.md
  sidebars.js
Labels: documentation

#958 Visual E2E setup - new examples
  docs/visual/e2e-testing/setup.md
Labels: documentation

#955 API Project/Team access settings
  docs/api-testing/project-access.md
  sidebars.js
  static/img/api-fortress/2021/12/accessOrg1.png
  static/img/api-fortress/2021/12/accessOrg2.png
  static/img/api-fortress/2021/12/emptyState.png
Labels: documentation, enhancement

#890 Quickstart new landpage
  cypress.json
  docusaurus.config.js
  package.json
  src/css/custom.css
  src/css/homesearchbar.css
  src/pages/community.js
  src/pages/home-callouts.js
  src/pages/index.js
  src/pages/quickstart.js
  src/pages/resources.js
  src/theme/Footer/index.js
  src/theme/SearchBar/index.js
  src/theme/SearchBar/styles.css
  src/theme/SearchBar/styles.module.css
  static/img/logo-saucelabs-white.svg
  static/img/logo-saucelabs.svg
  static/img/quickstart/appium.svg
  static/img/quickstart/cypress.svg
  static/img/quickstart/espresso.png
  static/img/quickstart/playwright.png
  static/img/quickstart/playwright.svg
  static/img/quickstart/puppeteer.svg
  static/img/quickstart/selenium.svg
  static/img/quickstart/testcafe.svg
  static/img/quickstart/xcuitest.png
  tests/cypress/integration/index.test.js
Labels: enhancement

#965 SC quickstart, install, setups
  docs/dev/cli/sauce-connect-proxy.md
  docs/secure-connections/sauce-connect/installation.md
  docs/secure-connections/sauce-connect/proxy-tunnels.md
  docs/secure-connections/sauce-connect/quickstart.md
  docs/secure-connections/sauce-connect/setup-configuration/basic-setup.md
  docs/secure-connections/sauce-connect/setup-configuration/environment-variables.md
  docs/secure-connections/sauce-connect/setup-configuration/high-availability.md
  docs/secure-connections/sauce-connect/setup-configuration/specialized-environments.md
  docs/secure-connections/sauce-connect/system-requirements.md
  static/img/sauce-connect/scp-bin.png
Labels: documentation

#966 remove outdated oauth method
  docs/mobile-apps/faq.md
Labels: documentation

#964 SC YAML file configuration
  docs/secure-connections/sauce-connect/setup-configuration/yaml-config.md
  static/img/sauce-connect/sc-config1.png
  static/img/sauce-connect/sc-config2.png
Labels: documentation

#968 Env variables echo confirmation -- Windows
  docs/basics/environment-variables.md
Labels: bug

#967 API Testing: Sauce Connect stickiness feature
  docs/api-testing/sauce-connect.md
  static/img/api-fortress/2021/12/api-sc-tunnel-error.png
Labels: documentation, enhancement

#973 Visual E2E setup
  docs/visual/e2e-testing/setup.md
Labels: documentation
