Repository saucelabs/sauce-docs, pull requests merged in 2021-06, with the labels that each got.

#403 Tcd 1539
  docs/basics/integrations/deque.md
Labels: documentation

#426 rm cli-proposal doc
  docs/cli-format-proposal.md
  docs/visual/component-testing/acct-team-mgmt.md
  docs/visual/component-testing/dashboard-workflow.md
  docs/visual/component-testing/integrations.md
  docs/visual/component-testing/interactions-testing-api.md
  docs/visual/component-testing/settings.md
  docs/visual/component-testing/setup.md
  docs/visual/component-testing/supported-browsers-devices.md
  docs/visual/e2e-testing/acct-team-mgmt.md
  docs/visual/e2e-testing/dashboard-workflow.md
  docs/visual/e2e-testing/integrations.md
  docs/visual/e2e-testing/recording-tests.md
  docs/visual/e2e-testing/secure-connections.md
  docs/visual/e2e-testing/settings.md
  docs/visual/e2e-testing/setup.md
  sidebars.js
  static/img/visual/e2e-add-project.png
Labels: bug

#436 visual e2e
  docs/visual/e2e-testing/integrations/continuous-integration.md
  docs/visual/e2e-testing/integrations/integrations.md
  docs/visual/e2e-testing/integrations/selenium-webdriver.md
  docs/visual/e2e-testing/rest-api.md
  docs/visual/e2e-testing/setup.md
  sidebars.js
  static/img/visual/e2e-add-browser.png
  static/img/visual/e2e-add-group-screener.png
  static/img/visual/e2e-add-group.png
  static/img/visual/e2e-add-page-button.png
  static/img/visual/e2e-add-page.png
  static/img/visual/e2e-add-test-group-on-client.png
  static/img/visual/e2e-api-key.png
  static/img/visual/e2e-group-id.png
  static/img/visual/e2e-history.png
  static/img/visual/e2e-run-test-button.png
  static/img/visual/e2e-test-complete.png
Labels: documentation

#447 Added CI page
  docs/visual/e2e-testing/integrations/continuous-integration.md
  docs/visual/e2e-testing/integrations/integrations.md
Labels: documentation

#459 Merge with master and update w3c doc
  docs/dev/w3c-webdriver-capabilities.md
  docs/visual/e2e-testing/integrations.md
  docs/visual/e2e-testing/integrations/continuous-integration.md
  docs/visual/e2e-testing/setup.md
  sidebars.js
Labels: documentation

#463 W3C requirements changes
  docs/dev/w3c-webdriver-capabilities.md
  docs/visual/e2e-testing/integrations/continuous-integration.md
Labels: documentation

#470 convert wiki links to sauce docs
  docs/appium-capabilities.md
  docs/basics/platform-configurator.md
  docs/dev/cli/espresso-xcuitest/real-devices.md
  docs/dev/cli/espresso-xcuitest/virtual-devices.md
  docs/dev/cli/espresso-xcuitest/yaml-config.md
  docs/dev/cli/sauce-connect-proxy.md
  docs/dev/error-messages.md
  docs/dev/glossary.md
  docs/dev/test-configuration-options.md
  docs/dev/w3c-webdriver-capabilities.md
  docs/headless.md
  docs/mobile-apps/app-storage.md
  docs/mobile-apps/automated-testing.md
  docs/mobile-apps/automated-testing/appium.md
  docs/mobile-apps/automated-testing/appium/real-devices.md
  docs/mobile-apps/automated-testing/appium/virtual-devices.md
  docs/mobile-apps/automated-testing/espresso-xcuitest/real-devices.md
  docs/mobile-apps/automated-testing/espresso-xcuitest/virtual-devices.md
  docs/mobile-apps/faq.md
  docs/mobile-apps/features.md
  docs/mobile-apps/ms-app-center.md
  docs/mobile-apps/supported-devices.md
  docs/mobile-apps/virtual-usb.md
Labels: documentation

#471 Consolidated Appium Caps --> moved to Test Config Options
  docs/dev/error-messages.md
  docs/dev/test-configuration-options.md
  docs/mobile-apps.md
  docs/mobile-apps/automated-testing/appium/real-devices.md
  docs/mobile-apps/automated-testing/appium/virtual-devices.md
  docs/mobile-apps/automated-testing/espresso-xcuitest/real-devices.md
Labels: documentation

#476 Changed 'sauce-storage' code snippets to 'storage:filename'
  docs/basics/test-config-annotation/test-config.md
  docs/dev/error-messages.md
  docs/dev/glossary.md
  docs/dev/test-configuration-options.md
  docs/mobile-apps/automated-testing/appium/appium-migration.md
  docs/mobile-apps/automated-testing/appium/real-devices.md
  docs/mobile-apps/automated-testing/appium/virtual-devices.md
  docs/mobile-apps/automated-testing/espresso-xcuitest/virtual-devices.md
  docs/mobile-apps/supported-devices.md
  docs/web-apps/automated-testing/pre-run-executables.md
Labels: documentation

#477 Re-wrote Mobile > Features (part of TCD-1609)
  docs/mobile-apps/features.md
Labels: documentation

#478 visual doc additions
  docs/visual/e2e-testing/api.md
  docs/visual/e2e-testing/dashboard-workflow.md
  docs/visual/e2e-testing/integrations/continuous-integration.md
  docs/visual/e2e-testing/integrations/github.md
  docs/visual/e2e-testing/integrations/sauce-labs.md
  docs/visual/e2e-testing/integrations/webhooks.md
  docs/visual/e2e-testing/rest-api.md
  docs/visual/e2e-testing/secure-connections.md
  docs/visual/e2e-testing/settings.md
  sidebars.js
  static/img/visual/e2e-github-status.png
  static/img/visual/e2e-report.png
  static/img/visual/e2e-state.png
  static/img/visual/e2e-states.png
Labels: documentation

#479 Visual component docs
  docs/visual/component-testing/acct-team-mgmt.md
  docs/visual/component-testing/cross-browser-testing.md
  docs/visual/component-testing/dashboard-workflow.md
  docs/visual/component-testing/integrations.md
  docs/visual/component-testing/integrations/continuous-integration.md
  docs/visual/component-testing/integrations/github.md
  docs/visual/component-testing/integrations/sauce-labs.md
  docs/visual/component-testing/integrations/slack.md
  docs/visual/component-testing/integrations/visual-studio.md
  docs/visual/component-testing/integrations/webhooks.md
  docs/visual/component-testing/interactions-testing-api.md
  docs/visual/component-testing/interactions-testing.md
  docs/visual/component-testing/settings.md
  docs/visual/component-testing/setup.md
  docs/visual/component-testing/supported-browsers-devices.md
  docs/visual/component-testing/supported-devices.md
  docs/visual/e2e-testing/acct-team-mgmt.md
  docs/visual/e2e-testing/api.md
  docs/visual/e2e-testing/integrations.md
  docs/visual/e2e-testing/integrations/sauce-labs.md
  docs/visual/e2e-testing/integrations/selenium-webdriver.md
  docs/visual/e2e-testing/recording-tests.md
  docs/visual/e2e-testing/screener-recorder.md
  docs/visual/e2e-testing/settings.md
  docs/visual/e2e-testing/setup.md
  sidebars.js
  static/img/visual/e2e-saucelabs-add-browser.png
  static/img/visual/e2e-saucelabs-integrations-button.png
  static/img/visual/e2e-saucelabs-integrations-settings.png
  static/img/visual/e2e-screener-recorder.png
Labels: documentation

#480 Visual docs buildout
  docs/visual/component-testing/setup.md
  docs/visual/e2e-testing/dashboard-workflow.md
  docs/visual/e2e-testing/screener-recorder.md
  docs/visual/e2e-testing/setup.md
  static/img/visual/e2e-recorder-empty.png
  static/img/visual/e2e-recorder-play.png
  static/img/visual/e2e-recorder-recording.png
  static/img/visual/e2e-recorder-save.png
  static/img/visual/e2e-state-accept-reject.png
  static/img/visual/e2e-state-changes.png
  static/img/visual/e2e-wait-for-element.png
Labels: documentation

#481 Visual e2e docs
  docs/visual/e2e-testing/acct-team-mgmt.md
  docs/visual/e2e-testing/settings.md
  static/img/visual/e2e-add-account-name.png
  static/img/visual/e2e-add-project-another-account.png
  static/img/visual/e2e-add-project-team-save.png
  static/img/visual/e2e-add-project-team.png
  static/img/visual/e2e-add-team-another-account.png
  static/img/visual/e2e-add-team-button.png
  static/img/visual/e2e-add-team.png
  static/img/visual/e2e-add-user-button.png
  static/img/visual/e2e-add-user-team-save.png
  static/img/visual/e2e-add-user-team.png
  static/img/visual/e2e-add-webhook.png
  static/img/visual/e2e-email-subscribe.png
  static/img/visual/e2e-hipchat-api-token.png
  static/img/visual/e2e-hipchat-room-id.png
  static/img/visual/e2e-hipchat-settings-menu.png
  static/img/visual/e2e-overview-activity-webhook-menu.png
  static/img/visual/e2e-slack-config-integrations.png
  static/img/visual/e2e-slack-notification.png
  static/img/visual/e2e-slack-webhook-url.png
Labels: documentation

#483 Visual docs - inclusive terminology corrections
  docs/visual/component-testing/cross-browser-testing.md
Labels: documentation

#485 Visual docs hub page
  docs/visual.md
  docs/visual/component-testing/dashboard-workflow.md
  docs/visual/component-testing/integrations/continuous-integration.md
  docs/visual/component-testing/settings.md
  docs/visual/component-testing/setup.md
  static/img/visual/component-review-button.png
  static/img/visual/component-review-state.jpeg
Labels: documentation

#486 Visual e2e, component, sidebars
  docs/visual.md
  docs/visual/component-testing/acct-team-mgmt.md
  docs/visual/component-testing/cross-browser-testing.md
  docs/visual/component-testing/dashboard-workflow.md
  docs/visual/component-testing/integrations/continuous-integration.md
  docs/visual/component-testing/integrations/github.md
  docs/visual/component-testing/integrations/sauce-labs.md
  docs/visual/component-testing/integrations/slack.md
  docs/visual/component-testing/integrations/visual-studio.md
  docs/visual/component-testing/integrations/webhooks.md
  docs/visual/component-testing/interactions-testing.md
  docs/visual/component-testing/notifications.md
  docs/visual/component-testing/supported-devices.md
  docs/visual/component-testing/testing-interactions.md
  docs/visual/e2e-testing/notifications.md
  sidebars.js
  static/img/visual/component-add-account-name.png
  static/img/visual/component-add-project-another-account.png
  static/img/visual/component-add-project-team-save.png
  static/img/visual/component-add-project-team.png
  static/img/visual/component-add-team-another-account.png
  static/img/visual/component-add-team-button.png
  static/img/visual/component-add-team.png
  static/img/visual/component-add-user-button.png
  static/img/visual/component-add-user-team-save.png
  static/img/visual/component-add-user-team.png
  static/img/visual/component-add-webhook.png
  static/img/visual/component-branching-merging.png
  static/img/visual/component-change-detail-flow.gif
  static/img/visual/component-github-status.png
  static/img/visual/component-ignore-flow.gif
  static/img/visual/component-notifications-settings.png
  static/img/visual/component-review-accept.png
  static/img/visual/component-review-complete.png
  static/img/visual/component-review-next.png
  static/img/visual/component-review-screenshots.jpeg
  static/img/visual/component-slack-notification.png
  static/img/visual/component-visual-history-flow.gif
  static/img/visual/component-vsts-status.png
  static/img/visual/component-webhooks.png
Labels: documentation

#420 misc porting changes
  docs/mobile-apps/automated-testing/espresso-xcuitest/real-devices.md
  docs/mobile-apps/automated-testing/espresso-xcuitest/virtual-devices.md
  docs/mobile-apps/creating-ipa-files.md
  docs/mobile-apps/faq.md
Labels: documentation

#489 Visual e2e docs changes
  docs/visual/e2e-testing/notifications.md
  docs/visual/e2e-testing/screener-recorder.md
  static/img/visual/e2e-add-browser-validation-options.png
  static/img/visual/e2e-delay-screenshot.png
  static/img/visual/e2e-execute-script.png
  static/img/visual/e2e-recorder-ignore.png
  static/img/visual/e2e-test-group-ignore.png
  static/img/visual/e2e-wait-for-visible.png
Labels: documentation

#424 Sc 3262
  babel.config.js
  docs/secure-connections/sauce-connect/installation.md
  docusaurus.config.js
  package.json
  src/components/scTable.jsx
  src/components/segment.js
  static/mock/versions.json
Labels: bug, documentation

#496 Clarify Data Center Association in Jira Integration
  docs/basics/integrations/jira.md
Labels: bug, documentation
