Repository saucelabs/sauce-docs, pull requests merged in 2021-02, with the labels that each got.

#178 appium, native fw, sidebars
  docs/dev/cli/espresso-xcuitest.md
  docs/mobile-apps.md
  docs/mobile-apps/automated-testing/appium/capabilities-scripts.md
  docs/mobile-apps/automated-testing/appium/rdc-performance.md
  docs/mobile-apps/automated-testing/appium/real-devices.md
  docs/mobile-apps/automated-testing/appium/virtual-devices.md
  docs/mobile-apps/automated-testing/espresso-xcuitest.md
  docs/mobile-apps/automated-testing/espresso-xcuitest/example-configurations.md
  docs/mobile-apps/automated-testing/espresso-xcuitest/real-devices.md
  docs/mobile-apps/automated-testing/espresso-xcuitest/virtual-devices.md
  docs/mobile-apps/devices.md
  docs/mobile-apps/faq.md
  sidebars.js
Labels: documentation

#179 appium.md
  docs/mobile-apps/automated-testing/appium.md
  docs/mobile-apps/automated-testing/espresso-xcuitest/real-devices.md
  docs/mobile-apps/automated-testing/espresso-xcuitest/virtual-devices.md
Labels: documentation

#180 appium, devices
  docs/mobile-apps/automated-testing/appium.md
  docs/mobile-apps/devices.md
  sidebars.js
Labels: documentation

#181 delete appium caps doc
  docs/mobile-apps/automated-testing/appium/capabilities-scripts.md
  docs/mobile-apps/devices.md
  sidebars.js
Labels: documentation

#182 appium, vusb, native fw
  docs/mobile-apps/automated-testing/espresso-xcuitest/example-configurations.md
  docs/mobile-apps/automated-testing/espresso-xcuitest/real-devices.md
  docs/mobile-apps/automated-testing/espresso-xcuitest/virtual-devices.md
  docs/mobile-apps/virtual-usb.md
  sidebars.js
Labels: documentation

#183 Doc/saucectl
  docs/testrunner-toolkit/running-tests.md
  docs/testrunner-toolkit/saucectl.md
  docs/web-apps/automated-testing/cypress.md
  sidebars.js
Labels: documentation

#186 Update configuration.md
  docs/testrunner-toolkit/configuration.md
Labels: documentation

#188 native fw rdc
  docs/mobile-apps/automated-testing/espresso-xcuitest/real-devices.md
Labels: documentation

#193 Update configuration.md
  docs/testrunner-toolkit/configuration.md
Labels: documentation

#197 Appium VDC
  docs/mobile-apps/automated-testing.md
  docs/mobile-apps/automated-testing/appium/real-devices.md
  docs/mobile-apps/automated-testing/appium/virtual-devices.md
  docs/mobile-apps/automated-testing/devices.md
  sidebars.js
Labels: documentation

#198 mobile app FAQ, CLI
  docs/dev/cli/espresso-xcuitest.md
  docs/mobile-apps/automated-testing/espresso-xcuitest/real-devices.md
  docs/mobile-apps/faq.md
Labels: documentation

#199 secure connections, ipsec
  docs/secure-connections.md
  docs/secure-connections/ipsec-vpn.md
  docs/visual.md
Labels: documentation

#202 SC CLI and changelog
  docs/dev/cli/espresso-xcuitest.md
  docs/dev/cli/sauce-connect-proxy.md
  docs/secure-connections/sauce-connect/changelog.md
  docs/secure-connections/sauce-connect/environment-variables.md
  sidebars.js
Labels: documentation

#203 SC CLI and ev
  docs/dev/cli/sauce-connect-proxy.md
  docs/secure-connections/sauce-connect/environment-variables.md
Labels: documentation

#204 SC docs
  docs/secure-connections/ipsec-vpn.md
  docs/secure-connections/sauce-connect/download.md
  docs/secure-connections/sauce-connect/environment-variables.md
  docs/visual.md
  sidebars.js
  static/img/sauce-connect/sc-download.png
Labels: documentation

#206 updated yarn lock
  .github/workflows/deploy.yml
  docusaurus.config.js
  package.json
  yarn.lock
Labels: bug

#207 hide TOC for CLI docs
  docs/dev/cli/espresso-xcuitest.md
  docs/dev/cli/sauce-connect-proxy.md
  docs/secure-connections/sauce-connect/environment-variables.md
Labels: documentation

#208 SC
  docs/basics/acct-team-mgmt/real-devices.md
  docs/secure-connections/sauce-connect/system-requirements.md
  docs/web-apps/live-testing.md
  sidebars.js
  static/img/sauce-connect/data-center-ui.jpg
  tests/tr.toolkit.test.js
Labels: documentation

#210 SC CLI
  docs/dev/cli/sauce-connect-proxy.md
Labels: documentation

#211 Added GA ID
  docusaurus.config.js
Labels: enhancement

#217 SC, sidebars
  docs/mobile-apps/automated-testing/devices.md
  docs/secure-connections/sauce-connect.md
  docs/secure-connections/sauce-connect/download.md
  docs/secure-connections/sauce-connect/faq.md
  docs/secure-connections/sauce-connect/installation.md
  docs/secure-connections/sauce-connect/system-requirements.md
  sidebars.js
Labels: documentation
