Repository saucelabs/sauce-docs, pull requests merged in 2022-04, with the labels that each got.

#1120 SAUCE_JOB_ID variable, new advanced.md docs
  docs/web-apps/automated-testing/cypress/advanced.md
  docs/web-apps/automated-testing/cypress/yaml.md
  docs/web-apps/automated-testing/playwright/advanced.md
  docs/web-apps/automated-testing/playwright/yaml.md
  docs/web-apps/automated-testing/testcafe/advanced.md
  docs/web-apps/automated-testing/testcafe/yaml.md
  sidebars.js
Labels: documentation

#1124 Appium 2.0 beta clarifications
  docs/dev/test-configuration-options.md
  docs/dev/w3c-webdriver-capabilities.md
  docs/mobile-apps/automated-testing/appium/real-devices.md
Labels: documentation

#1134 Updating saucectl
  docs/dev/cli/saucectl.md
Labels: documentation

#1096 Bypass screenshot restriction
  docs/mobile-apps/features/bypass-screenshot.md
  docs/mobile-apps/live-testing/live-mobile-app-testing.md
  sidebars.js
Labels: documentation, enhancement

#1158 Added missing C# examples - Visual E2E commands
  docs/visual/e2e-testing/commands-options.md
Labels: documentation

#1084 SC 4.8.x supported OSs
  docs/secure-connections/sauce-connect/system-requirements.md
  static/img/sauce-connect/timeout-values.png
Labels: documentation

#1174 Visual Quickstart edits
  docs/visual/component-testing/setup.md
  docs/visual/e2e-testing/setup.md
  static/img/visual/component-expected-response.png
  static/img/visual/component-integration-results.png
  static/img/visual/component-quickstart-all-projects.png
Labels: documentation

#1199 [COM-203] Updated smoke tests
  webdriver/package-lock.json
  webdriver/test/specs/example.e2e.js
Labels: bug

#1182 Added EU-Central API Testing endpoint
  docs/api-testing/sauce-connect.md
  docs/secure-connections/sauce-connect/setup-configuration/specialized-environments.md
Labels: documentation

#1148 Add Azure DevOps integration details to CI section
  docs/ci/azure.md
  sidebars.js
Labels: documentation
