Repository saucelabs/sauce-docs, pull requests merged in 2022-01, with the labels that each got.

#979 Added Google Analytics and Search Console
  static/googlec6383495702fdb7c.html
  static/gtag.js
Labels: Backend

#980 Updated footer and 404 copyright year to 2022
  src/theme/Footer/index.js
  static/404.html
Labels: Backend

#985 Updated screenshots - new UI
  docs/api-testing/logger.md
  docs/api-testing/metrics-logs.md
  docs/api-testing/project-access.md
  docs/api-testing/quickstart.md
  docs/api-testing/schedule-test.md
  docs/api-testing/variables-environment-overrides.md
  docs/api-testing/variables-flexible-environments.md
  sidebars.js
  static/img/api-fortress/2021/02/dash-1.2.png
  static/img/api-fortress/2021/02/dash-1.5.png
  static/img/api-fortress/2021/02/dashboardFilters.png
  static/img/api-fortress/2021/02/dashboardLogs.png
  static/img/api-fortress/2021/02/metrics.png
  static/img/api-fortress/2021/02/metricsFilters.png
Labels: documentation

#986 Cloning API tests feature
  docs/api-testing/clone-test.md
  docs/api-testing/import-export-tests.md
  docs/api-testing/metrics-logs.md
  docs/api-testing/schedule-test.md
  sidebars.js
  static/img/api-testing/import-tests/clone.png
Labels: documentation

#981 Legacy Migration Guide (APIF to Sauce)
  docs/api-testing/environments.md
  docs/api-testing/import-export-tests.md
  docs/api-testing/legacy.md
  docs/api-testing/variables-environment-overrides.md
  docs/api-testing/vault.md
  sidebars.js
  static/img/api-testing/import-tests/authenticated-api.png
  static/img/api-testing/import-tests/create-test.png
  static/img/api-testing/import-tests/export-selected.png
  static/img/api-testing/import-tests/select-all.png
  static/img/api-testing/import-tests/test1.png
  static/img/api-testing/import-tests/upload-archive.png
Labels: documentation

#991 Manual redirects for Postman and Schedule test URLs
  docs/api-testing/importing-postman-collections.md
  docs/api-testing/schedule-a-test.md
Labels: bug

#996 Test config options link fix
  docs/dev/test-configuration-options.md
Labels: bug

#959 Visual E2E: added Test Timeouts guidance
  docs/visual/e2e-testing/setup.md
Labels: documentation

#1016 Visual Quickstart edits
  docs/visual/component-testing/setup.md
  docs/visual/e2e-testing/setup.md
Labels: documentation

#1019 SC CLI --logfile
  docs/dev/cli/sauce-connect-proxy.md
Labels: documentation

#1020 Visual E2E and Composer QS
  docs/visual/component-testing/setup.md
  docs/visual/e2e-testing/setup.md
Labels: documentation

#1007 API Testing | PageDuty, Webhook Connectors
  docs/api-testing/integrations/apifctl-cicd-integration.md
  docs/api-testing/integrations/pagerduty-webhooks.md
  docs/api-testing/legacy.md
  docs/api-testing/project-access.md
  docs/api-testing/variables-environment-overrides.md
  sidebars.js
  static/img/api-fortress/2021/04/sampleHook.png
  static/img/api-fortress/2022/pagerduty-template.png
Labels: documentation, enhancement

#1008 API Testing | Builds, Dashboard, apifctl
  docs/api-testing/composer/other-components.md
  docs/api-testing/integrations/apifctl-cicd-integration.md
  docs/api-testing/project-dashboard.md
  sidebars.js
  static/img/api-testing/dashboard/builds1.png
  static/img/api-testing/dashboard/builds2.png
Labels: documentation, enhancement

#1023 Minor changes in SC CLI docs
  docs/dev/cli/sauce-connect-proxy.md
  docs/secure-connections/sauce-connect/setup-configuration/yaml-config.md
Labels: documentation

#1028 added forethought script
  docusaurus.config.js
Labels: enhancement

#1029 adjusted back to top button styles
  src/theme/BackToTopButton/index.js
  src/theme/BackToTopButton/styles.module.css
Labels: bug

#1030 added gitpod.yml
  .github/workflows/deploy.yml
  .gitpod.yml
Labels: enhancement
