Repository saucelabs/sauce-docs, pull requests merged in 2022-02, with the labels that each got.

#1027 sc.exe formatting
  docs/secure-connections/sauce-connect/proxy-tunnels.md
  docs/secure-connections/sauce-connect/setup-configuration/additional-proxies.md
  docs/secure-connections/sauce-connect/setup-configuration/basic-setup.md
  docs/secure-connections/sauce-connect/setup-configuration/high-availability.md
Labels: documentation

#1033 Visual quickstart/setup changes
  docs/visual/component-testing/setup.md
  docs/visual/e2e-testing/setup.md
Labels: documentation

#1036 Revised SC Quickstart
  docs/secure-connections/sauce-connect/quickstart.md
  static/img/sauce-connect/cli-tunnel-confirmation.png
  static/img/sauce-connect/cli-tunnel-stop.png
  static/img/sauce-connect/tunnelsPage.png
  static/img/sauce-connect/tunnelsuccess-ui.png
Labels: documentation

#1039 Revised API Quickstart for new UI
  docs/api-testing/quickstart.md
  static/img/api-fortress/2021/01/createProject.png
  static/img/api-fortress/2021/01/enterRequestSave.png
  static/img/api-fortress/2021/01/generateTest.png
  static/img/api-fortress/2021/01/newProject.png
  static/img/api-fortress/2021/01/testDetails.png
  static/img/api-fortress/2021/01/testRuns.png
  static/img/api-fortress/2021/01/testSuccess.png
  static/img/api-fortress/2021/02/testCode.png
  static/img/api-fortress/2021/02/testVisual.png
Labels: documentation

#1037 Added hide script for forethought box
  docusaurus.config.js
  src/css/custom.css
  static/scripts/hide.js
Labels: bug

#1045 Updated search index
  .docsearch/config.json
  docusaurus.config.js
Labels: enhancement

#1047 refactored url transform from relative path to absolute path
  src/theme/SearchBar/index.js
Labels: bug

#1052 Add note that Safari 15+ can't use `.local` domains
  docs/secure-connections/sauce-connect/faq.md
Labels: documentation

#1071 added deploy-to-dev workflow
  .github/workflows/deploy-to-dev.yml
Labels: enhancement

#1078 noIndex tag test
  docs/api-testing/on-prem/quick-start.md
Labels: Backend

#1091 Minor change to PagerDuty doc
  docs/api-testing/integrations/pagerduty-webhooks.md
Labels: documentation
